import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  data: [
    {
      Category: "Drama",
      Name: "everything everywhere all at once",
      Id: "1",
      img: "1.jpg",
      Date: 2022,
      Part: "2020s",
      Subject:
        "An aging Chinese immigrant is swept up in an insane adventure, where she alone can save what’s important to her by connecting with the lives she could have led in other universes.",
      Director: "Daniel Scheinert, Daniel Kwan",
    },
    {
      Category: "Action",
      Name: "the last duel",
      Id: "2",
      img: "2.jpg",
      Date: 2021,
      Part: "2020s",
      Subject:
        "King Charles VI declares that Knight Jean de Carrouges settle his dispute with his squire by challenging him to a duel.",
      Director: "Ridley Scott",
    },
    {
      Category: "Science Fiction",
      Name: "dune",
      Id: "3",
      img: "3.jpg",
      Date: 2021,
      Part: "2020s",
      Subject:
        "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet’s exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity’s greatest potential-only those who can conquer their fear will survive.",
      Director: " Denis Villeneuve",
    },
    {
      Category: "Drama",
      Name: "drive my car",
      Id: "4",
      img: "4.jpg",
      Date: 2021,
      Part: "2020s",
      Subject:
        "Yusuke Kafuku, a stage actor and director, still unable, after two years, to cope with the loss of his beloved wife, accepts to direct Uncle Vanja at a theater festival in Hiroshima. There he meets Misaki, an introverted young woman, appointed to drive his car. In between rides, secrets from the past and heartfelt confessions will be unveiled.",
      Director: "Ryusuke Hamaguchi",
    },
    {
      Category: "Drama",
      Name: "the worst person in the world",
      Id: "5",
      img: "5.jpg",
      Date: 2021,
      Part: "2020s",
      Subject:
        "Chronicles four years in the life of Julie, a young woman who navigates the troubled waters of her love life and struggles to find her career path, leading her to take a realistic look at who she really is.",
      Director: "Joachim Trier",
    },
    {
      Category: "Drama",
      Name: "good will hunting",
      Id: "6",
      img: "6.jpg",
      Date: 1997,
      Part: "Older...",
      Subject:
        "Will Hunting has a genius-level IQ but chooses to work as a janitor at MIT. When he solves a difficult graduate-level math problem, his talents are discovered by Professor Gerald Lambeau, who decides to help the misguided youth reach his potential. When Will is arrested for attacking a police officer, Professor Lambeau makes a deal to get leniency for him if he will get treatment from therapist Sean Maguire.",
      Director: "Gus Van Sant",
    },
    {
      Category: "Drama",
      Name: "her",
      Id: "7",
      img: "7.jpg",
      Date: 2013,
      Part: "2010s",
      Subject:
        "In the not so distant future, Theodore, a lonely writer purchases a newly developed operating system designed to meet the user’s every needs. To Theodore’s surprise, a romantic relationship develops between him and his operating system. This unconventional love story blends science fiction and romance in a sweet tale that explores the nature of love and the ways that technology isolates and connects us all.",
      Director: "Spike Jonze",
    },
    {
      Category: "Drama",
      Name: "undine",
      Id: "8",
      img: "8.jpg",
      Date: 2020,
      Part: "2020s",
      Subject:
        "Undine works as a historian lecturing on Berlin’s urban development. When the man she loves leaves her, the ancient myth catches up with her. But falling in love anew, Undine reworks the myth of the mysterious water spirit as a modern fairy-tale in a disenchanted world.",
      Director: "Christian Petzold",
    },
    {
      Category: "Drama",
      Name: "parasite",
      Id: "9",
      img: "9.jpg",
      Date: 2019,
      Part: "2010s",
      Subject:
        "All unemployed, Ki-taek’s family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
      Director: "Bong Joon-ho",
    },
    {
      Category: "Drama",
      Name: "gone girl",
      Id: "10",
      img: "10.jpg",
      Date: 2014,
      Part: "2010s",
      Subject:
        "With his wife’s disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it’s suspected that he may not be innocent.",
      Director: "David Fincher",
    },
    {
      Category: "Drama",
      Name: "birdman",
      Id: "11",
      img: "11.jpg",
      Date: 2014,
      Part: "2010s",
      Subject:
        "A portrait of Robert, a troubled but poetic soul struggling with his purgatorial existence in a hackney scrapyard.",
      Director: "Guy Bolongaro",
    },
    {
      Category: "Drama",
      Name: "frances ha",
      Id: "12",
      img: "12.jpg",
      Date: 2012,
      Part: "2010s",
      Subject:
        "An aspiring dancer moves to New York City and becomes caught up in a whirlwind of flighty fair-weather friends, diminishing fortunes and career setbacks.",
      Director: "Noah Baumbach",
    },
    {
      Category: "Drama",
      Name: "mr nobody",
      Id: "13",
      img: "13.jpg",
      Date: 2009,
      Part: "2000s",
      Subject:
        "Nemo Nobody leads an ordinary existence with his wife and 3 children; one day, he wakes up as a mortal centenarian in the year 2092.",
      Director: "Jaco Van Dormael",
    },
    {
      Category: "Drama",
      Name: "the curious case of benjamin button",
      Id: "14",
      img: "14.jpg",
      Date: 2008,
      Part: "2000s",
      Subject:
        "Born under unusual circumstances, Benjamin Button springs into being as an elderly man in a New Orleans nursing home and ages in reverse. Twelve years after his birth, he meets Daisy, a child who flits in and out of his life as she grows up to be a dancer. Though he has all sorts of unusual adventures over the course of his life, it is his relationship with Daisy, and the hope that they will come together at the right time, that drives Benjamin forward.",
      Director: "David Fincher",
    },
    {
      Category: "Drama",
      Name: "vicky cristina barcelona",
      Id: "15",
      img: "15.jpg",
      Date: 2008,
      Part: "2000s",
      Subject:
        "Two girlfriends on a summer holiday in Spain become enamored with the same painter, unaware that his ex-wife, with whom he has a tempestuous relationship, is about to re-enter the picture.",
      Director: "Woody Allen",
    },
    {
      Category: "Drama",
      Name: "lost in translation",
      Id: "16",
      img: "16.jpg",
      Date: 2003,
      Part: "2000s",
      Subject:
        "Two lost souls visiting Tokyo  the young, neglected wife of a photographer and a washed-up movie star shooting a TV commercial  find an odd solace and pensive freedom to be real in each other’s company, away from their lives in America.",
      Director: "Sofia Coppola",
    },
    {
      Category: "Drama",
      Name: "memories of murder",
      Id: "17",
      img: "17.jpg",
      Date: 2003,
      Part: "2000s",
      Subject:
        "1986 Gyunggi Province. The body of a young woman is found brutally raped and murdered. Two months later, a series of rapes and murders commences under similar circumstances. And in a country that had never known such crimes, the dark whispers about a serial murderer grow louder. A special task force is set up in the area, with two local detectives Park Doo-Man and Jo Young-Goo joined by a detective from Seoul who requested to be assigned to the case.",
      Director: "Bong Joon-ho",
    },
    {
      Category: "Drama",
      Name: "leon the professional",
      Id: "18",
      img: "18.jpg",
      Date: 1994,
      Part: "Older...",
      Subject:
        "Léon, the top hit man in New York, has earned a rep as an effective “cleaner”. But when his next-door neighbors are wiped out by a loose-cannon DEA agent, he becomes the unwilling custodian of 12-year-old Mathilda. Before long, Mathilda’s thoughts turn to revenge, and she considers following in Léon’s footsteps.",
      Director: "Luc Besson",
    },
    {
      Category: "Drama",
      Name: "cinema paradiso",
      Id: "19",
      img: "19.jpg",
      Date: 1988,
      Part: "Older...",
      Subject:
        "A filmmaker recalls his childhood, when he fell in love with the movies at his village’s theater and formed a deep friendship with the theater’s projectionist.",
      Director: "Giuseppe Tornatore",
    },
    {
      Category: "Drama",
      Name: "one flew over the cuckoo’s nest",
      Id: "20",
      img: "20.jpg",
      Date: 1975,
      Part: "Older...",
      Subject:
        "While serving time for insanity at a state mental hospital, implacable rabble-rouser, Randle Patrick McMurphy, inspires his fellow patients to rebel against the authoritarian rule of head nurse, Mildred Ratched.",
      Director: "Miloš Forman",
    },
    {
      Category: "Drama",
      Name: "12 angry men",
      Id: "21",
      img: "21.jpg",
      Date: 1957,
      Part: "Older...",
      Subject:
        "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors’ prejudices and preconceptions about the trial, the accused, and each other.",
      Director: "Sidney Lumet",
    },
    {
      Category: "Drama",
      Name: "the broken landlord",
      Id: "22",
      img: "22.jpg",
      Date: 1985,
      Part: "Older...",
      Subject:
        "The landowner (Agha) of the Haraptar village marries off his old father with the young and beautiful Kiraz. But on the nuptial night, his father dies and everthing starts to go bad for the Agha. Due to the long drought and provocations of Kekec Salman (big brother of Kiraz), the peasants steal the crops and run away to Istanbul.",
      Director: "Nesli Çölgeçen",
    },
    {
      Category: "Action",
      Name: "the Breath",
      Id: "23",
      img: "23.jpg",
      Date: 2009,
      Part: "2000s",
      Subject:
        "A small task force of the Turkish army have to defend a relay station in the middle of nowhere against a possible terrorist raid.",
      Director: "Levent Semerci",
    },
    {
      Category: "Action",
      Name: "the nice guys",
      Id: "24",
      img: "24.jpg",
      Date: 2016,
      Part: "2010s",
      Subject:
        "A private eye investigates the apparent suicide of a fading porn star in 1970s Los Angeles and uncovers a conspiracy.",
      Director: "Shane Black",
    },
    {
      Category: "Action",
      Name: "sicario",
      Id: "25",
      img: "25.jpg",
      Date: 2015,
      Part: "2010s",
      Subject:
        "An idealistic FBI agent is enlisted by a government task force to aid in the escalating war against drugs at the border area between the U.S. and Mexico.",
      Director: "Denis Villeneuve",
    },
    {
      Category: "Action",
      Name: "Mad Max: Fury Road",
      Id: "26",
      img: "26.jpg",
      Date: 2015,
      Part: "2010s",
      Subject:
        "An apocalyptic story set in the furthest reaches of our planet, in a stark desert landscape where humanity is broken, and most everyone is crazed fighting for the necessities of life. Within this world exist two rebels on the run who just might be able to restore order.",
      Director: "George Miller",
    },
    {
      Category: "Action",
      Name: "sin city",
      Id: "27",
      img: "27.jpg",
      Date: 2014,
      Part: "2010s",
      Subject:
        "Welcome to Sin City. This town beckons to the tough, the corrupt, the brokenhearted. Some call it dark… Hard-boiled. Then there are those who call it home — Crooked cops, sexy dames, desperate vigilantes. Some are seeking revenge, others lust after redemption, and then there are those hoping for a little of both. A universe of unlikely and reluctant heroes still trying to do the right thing in a city that refuses to care.",
      Director: "Frank Miller",
    },
    {
      Category: "Action",
      Name: "snowpiercer",
      Id: "28",
      img: "28.jpg",
      Date: 2013,
      Part: "2010s",
      Subject:
        "In a future where a failed global-warming experiment kills off most life on the planet, a class system evolves aboard the Snowpiercer, a train that travels around the globe via a perpetual-motion engine.",
      Director: "Bong Joon-ho",
    },
    {
      Category: "Action",
      Name: "skyfall",
      Id: "29",
      img: "29.jpg",
      Date: 2012,
      Part: "2010s",
      Subject:
        "When Bond’s latest assignment goes gravely wrong and agents around the world are exposed, MI6 is attacked forcing M to relocate the agency. These events cause her authority and position to be challenged by Gareth Mallory, the new Chairman of the Intelligence and Security Committee.",
      Director: "Sam Mendes",
    },
    {
      Category: "Action",
      Name: "kill bill: the whole bloody affair",
      Id: "30",
      img: "30.jpg",
      Date: 2011,
      Part: "2010s",
      Subject:
        "An assassin is shot and almost killed by her ruthless employer, Bill, and other members of their assassination circle  but she lives to plot her vengeance. Kill Bill: The Whole Bloody Affair is a complete edit of the two-part martial arts action films Kill Bill: Vol. 1 and Kill Bill: Vol. 2. The film was originally scheduled to be released as one part. However, due to the film’s over 4 hour running time, it was split into two parts.",
      Director: "Quentin Tarantino",
    },
    {
      Category: "Action",
      Name: "rocknrolla",
      Id: "31",
      img: "31.jpg",
      Date: 2008,
      Part: "Older...",
      Subject:
        "When a Russian mobster sets up a real estate scam that generates millions of pounds, various members of London’s criminal underworld pursue their share of the fortune. Various shady characters, including Mr One-Two, Stella the accountant, and Johnny Quid, a druggie rock-star, try to claim their slice.",
      Director: "Guy Ritchie",
    },
    {
      Category: "Action",
      Name: "top gun  maverick",
      Id: "32",
      img: "32.jpg",
      Date: 2022,
      Part: "2020s",
      Subject:
        "After more than thirty years of service as one of the Navy’s top aviators, and dodging the advancement in rank that would ground him, Pete “Maverick” Mitchell finds himself training a detachment of TOP GUN graduates for a specialized mission the likes of which no living pilot has ever seen. Facing an uncertain future and confronting the ghosts of his past, Maverick is drawn into a confrontation with his own deepest fears, culminating in a mission that demands the ultimate sacrifice from those who will be chosen to fly it",
      Director: "Joseph Kosinski",
    },
    {
      Category: "Action",
      Name: "children of men",
      Id: "33",
      img: "33.jpg",
      Date: 2006,
      Part: "2000s",
      Subject:
        "In 2027, in a chaotic world in which humans can no longer procreate, a former activist agrees to help transport a miraculously pregnant woman to a sanctuary at sea, where her child’s birth may help scientists save the future of humankind.",
      Director: "Alfonso Cuarón",
    },
    {
      Category: "Action",
      Name: "constantine",
      Id: "34",
      img: "34.jpg",
      Date: 2005,
      Part: "2000s",
      Subject:
        "John Constantine has literally been to Hell and back. When he teams up with a policewoman to solve the mysterious suicide of her twin sister, their investigation takes them through the world of demons and angels that exists beneath the landscape of contemporary Los Angeles.",
      Director: "Francis Lawrence",
    },
    {
      Category: "Action",
      Name: "blade",
      Id: "35",
      img: "35.jpg",
      Date: 1998,
      Part: "Older...",
      Subject:
        "When Blade’s mother was bitten by a vampire during pregnancy, she did not know that she gave her son a special gift while dying—all the good vampire attributes in combination with the best human skills. Blade and his mentor battle an evil vampire rebel who plans to take over the outdated vampire council, capture Blade and resurrect a voracious blood god.",
      Director: " Stephen Norrington",
    },
    {
      Category: "Action",
      Name: "kingdom of heaven",
      Id: "36",
      img: "36.jpg",
      Date: 2005,
      Part: "2000s",
      Subject:
        "After his wife dies, a blacksmith named Balian is thrust into royalty, political intrigue and bloody holy wars during the Crusades.",
      Director: "Ridley Scott",
    },
    {
      Category: "Action",
      Name: "battal gazi destanı",
      Id: "37",
      img: "37.jpg",
      Date: 1971,
      Part: "Older...",
      Subject:
        "Depiction of the life of the legendary Muslim Serdar of Malatya, Battal Gazi.",
      Director: "Atıf Yılmaz",
    },
    {
      Category: "Action",
      Name: "braveheart",
      Id: "38",
      img: "38.jpg",
      Date: 1995,
      Part: "Older...",
      Subject:
        "Enraged at the slaughter of Murron, his new bride and childhood love, Scottish warrior William Wallace slays a platoon of the local English lord’s soldiers. This leads the village to revolt and, eventually, the entire country to rise up against English rule.",
      Director: "Mel Gibson",
    },
    {
      Category: "Action",
      Name: "heat",
      Id: "39",
      img: "39.jpg",
      Date: 1995,
      Part: "Older...",
      Subject:
        "Obsessive master thief Neil McCauley leads a top-notch crew on various daring heists throughout Los Angeles while determined detective Vincent Hanna pursues him without rest. Each man recognizes and respects the ability and the dedication of the other even though they are aware their cat-and-mouse game may end in violence.",
      Director: "Michael Mann",
    },
    {
      Category: "Action",
      Name: "gladiator",
      Id: "40",
      img: "40.jpg",
      Date: 1999,
      Part: "Older...",
      Subject:
        "In the year 180, the death of emperor Marcus Aurelius throws the Roman Empire into chaos. Maximus is one of the Roman army’s most capable and trusted generals and a key advisor to the emperor. As Marcus’ devious son Commodus ascends to the throne, Maximus is set to be executed. He escapes, but is captured by slave traders. Renamed Spaniard and forced to become a gladiator, Maximus must battle to the death with other men for the amusement of paying audiences.",
      Director: "Ridley Scott",
    },
    {
      Category: "Action",
      Name: "the last samurai",
      Id: "41",
      img: "41.jpg",
      Date: 2003,
      Part: "2000s",
      Subject:
        "Nathan Algren is an American hired to instruct the Japanese army in the ways of modern warfare, which finds him learning to respect the samurai and the honorable principles that rule them. Pressed to destroy the samurai’s way of life in the name of modernization and open trade, Algren decides to become an ultimate warrior himself and to fight for their right to exist.",
      Director: "Edward Zwick",
    },
    {
      Category: "Action",
      Name: "troy",
      Id: "42",
      img: "42.jpg",
      Date: 2004,
      Part: "2000s",
      Subject:
        "In year 1250 B.C. during the late Bronze age, two emerging nations begin to clash. Paris, the Trojan prince, convinces Helen, Queen of Sparta, to leave her husband Menelaus, and sail with him back to Troy. After Menelaus finds out that his wife was taken by the Trojans, he asks his brother Agamemnom to help him get her back. Agamemnon sees this as an opportunity for power. So they set off with 1,000 ships holding 50,000 Greeks to Troy. With the help of Achilles, the Greeks are able to fight the never before defeated Trojans",
      Director: "Wolfgang Petersen",
    },
    {
      Category: "Comedy",
      Name: "the mitchells vs. the machines",
      Id: "43",
      img: "43.jpg",
      Date: 2021,
      Part: "2020s",
      Subject:
        "A quirky, dysfunctional family’s road trip is upended when they find themselves in the middle of the robot apocalypse and suddenly become humanity’s unlikeliest last hope.",
      Director: "Michael Rianda",
    },
    {
      Category: "Comedy",
      Name: "aile arasında",
      Id: "44",
      img: "44.jpg",
      Date: 2017,
      Part: "2010s",
      Subject:
        "The neurotic Fikret and tavern singer Solmaz, whose 21 year long relationships end on the same day, meet through a funny coincidence. When Solmaz’s daughter Zeynep decides to marry her lover from Adana, the ever-fearful Fikret ends up having to play the role of his life. Intended at first to be kept in the family, the wedding becomes a much bigger event upon the insistence of the groom’s relatives. Can our heroes come to terms with the traditional Adana family who carry guns and own a kebab restaurant chain, and see the wedding through without mishaps?",
      Director: " Ozan Açıktan",
    },
    {
      Category: "Comedy",
      Name: "just go with it",
      Id: "45",
      img: "45.jpg",
      Date: 2011,
      Part: "2010s",
      Subject:
        "A plastic surgeon, romancing a much younger schoolteacher, enlists his loyal assistant to pretend to be his soon to be ex-wife, in order to cover up a careless lie. When more lies backfire, the assistant’s kids become involved, and everyone heads off for a weekend in Hawaii that will change all their lives.",
      Director: "Dennis Dugan",
    },
    {
      Category: "Comedy",
      Name: "ada zombilerin düğünü",
      Id: "46",
      img: "46.jpg",
      Date: 2010,
      Part: "2010s",
      Subject:
        "Five people who knew each other for a long time a group of friends, to attend the wedding of a mutual friend goes to Buyukada. Erhan, weddings, and long intervals, the team can come together to be able to record their happy moments brought a camera, and is continuous. All throughout the film viewed, it is reflected from the camera. Later a group of wedding guests attacking zombie, turns into a mess of blood.",
      Director: "Talip Ertürk",
    },
    {
      Category: "Comedy",
      Name: "arog",
      Id: "47",
      img: "47.jpg",
      Date: 2008,
      Part: "2000s",
      Subject:
        "Commander Logar fools Arif and sends him 1.000.000 years back in the time. He must civilize people from past to reach today.",
      Director: "Ali Taner Baltaci",
    },
    {
      Category: "Comedy",
      Name: "the bucket list",
      Id: "48",
      img: "48.jpg",
      Date: 2007,
      Part: "2000s",
      Subject:
        "Corporate billionaire Edward Cole and working class mechanic Carter Chambers are worlds apart. At a crossroads in their lives, they share a hospital room and discover they have two things in common: a desire to spend the time they have left doing everything they ever wanted to do and an unrealized need to come to terms with who they are. Together they embark on the road trip of a lifetime, becoming friends along the way and learning to live life to the fullest, with insight and humor.",
      Director: "Rob Reiner",
    },
    {
      Category: "Comedy",
      Name: "hokkabaz",
      Id: "49",
      img: "49.jpg",
      Date: 2006,
      Part: "2000s",
      Subject:
        "Failed magician Iskender decides to do a tour to save his career, but has to bring his grumpy and senile father along. The tour is quite unexpectedly interrupted when a bride actually disappears from the stage.",
      Director: "Ali Taner Baltaci",
    },
    {
      Category: "Comedy",
      Name: "pardon",
      Id: "50",
      img: "50.jpg",
      Date: 2005,
      Part: "2000s",
      Subject:
        "Based on a true event, Pardon tells the tragicomic story of three friends who end up in prison when they are mistaken as members of a terrorist organization. Ibrahim’s fear of uniforms makes him runaway whenever he sees one. Because of this, police mistakes him with a terrorist and takes him and his friend Muzo into custody. Fooled by the police during the interrogation they name another friend, Aydin, in hope of saving themselves. As they all end up in prison, they remember the families and lovers they left behind.",
      Director: "Mert Baykal",
    },
    {
      Category: "Comedy",
      Name: "neredesin firuze",
      Id: "51",
      img: "51.jpg",
      Date: 2004,
      Part: "2000s",
      Subject:
        "Hayri and Orhan are two music producers head over heels in debt. In an attempt to find the next big thing to turn the business around, they contact Ferhat, a gastarbeiter in Germany, and desperately bring him to Istanbul to sign him. As they are struggling to find the necessary funds to promote Ferhat’s debut album, a mysterious rich woman named Firuze shows up and starts supporting them. The future now seems bright, but things are not always what they seem…",
      Director: "Ezel Akay",
    },
    {
      Category: "Comedy",
      Name: "vizontele",
      Id: "52",
      img: "52.jpg",
      Date: 2001,
      Part: "2000s",
      Subject:
        "The story takes place in a small town (called Hakkari) in Turkey at the beginning of the 70’s. The time has come to bring technology into that small town. The first Television (or called Visiontele by the citizens) arrives and the chaos begins.",
      Director: "Yılmaz Erdoğan",
    },
    {
      Category: "Comedy",
      Name: "hababam sınıfı",
      Id: "53",
      img: "53.jpg",
      Date: 1975,
      Part: "Older...",
      Subject:
        "Lazy, uneducated students mostly coming from money, share a very close band. They live together in the dormitory of this private highschool, where they daily plan their latest pranks on teachers or the other classes. When a new and obviously strict headmaster arrives, the students naturally try to overthrow him. A comic war of nitwits follows.",
      Director: "Ertem Eğilmez",
    },
    {
      Category: "Horror",
      Name: "the conjuring",
      Id: "54",
      img: "54.jpg",
      Date: 2021,
      Part: "2020s",
      Subject:
        "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse. Forced to confront a powerful entity, the Warrens find themselves caught in the most terrifying case of their lives.",
      Director: "James Wan",
    },
    {
      Category: "Horror",
      Name: "midsommar",
      Id: "55",
      img: "55.jpg",
      Date: 2019,
      Part: "2010s",
      Subject:
        "Several friends travel to Sweden to study as anthropologists a summer festival that is held every ninety years in the remote hometown of one of them. What begins as a dream vacation in a place where the sun never sets, gradually turns into a dark nightmare as the mysterious inhabitants invite them to participate in their disturbing festive activities.",
      Director: "Ari Aster",
    },
    {
      Category: "Horror",
      Name: "climax",
      Id: "56",
      img: "56.jpg",
      Date: 2018,
      Part: "2010s",
      Subject:
        "Young dancers gather in a remote and empty school building to rehearse on a cold and wintry night. The all-night celebration soon turns into a hallucinatory nightmare when they learn that their sangria is laced with LSD.",
      Director: "Gaspar Noé",
    },
    {
      Category: "Horror",
      Name: "a quiet place",
      Id: "57",
      img: "57.jpg",
      Date: 2018,
      Part: "2010s",
      Subject:
        "A family is forced to live in silence while hiding from creatures that hunt by sound.",
      Director: "John Krasinski",
    },
    {
      Category: "Horror",
      Name: "hereditary",
      Id: "58",
      img: "58.jpg",
      Date: 2018,
      Part: "2010s",
      Subject:
        "When Ellen, the matriarch of the Graham family, passes away, her daughter’s family begins to unravel cryptic and increasingly terrifying secrets about their ancestry.",
      Director: "Ari Aster",
    },
    {
      Category: "Horror",
      Name: "life",
      Id: "59",
      img: "59.jpg",
      Date: 2017,
      Part: "2010s",
      Subject:
        "The six-member crew of the International Space Station is tasked with studying a sample from Mars that may be the first proof of extra-terrestrial life, which proves more intelligent than ever expected.",
      Director: "Daniel Espinosa",
    },

    {
      Category: "Horror",
      Name: "get out",
      Id: "60",
      img: "60.jpg",
      Date: 2017,
      Part: "2010s",
      Subject:
        "Chris and his girlfriend Rose go upstate to visit her parents for the weekend. At first, Chris reads the family’s overly accommodating behavior as nervous attempts to deal with their daughter’s interracial relationship, but as the weekend progresses, a series of increasingly disturbing discoveries lead him to a truth that he never could have imagined.",
      Director: "Jordan Peele",
    },
    {
      Category: "Horror",
      Name: "the witch",
      Id: "61",
      img: "61.jpg",
      Date: 2015,
      Part: "2010s",
      Subject:
        "In 1630s New England, William and Katherine lead a devout Christian life with five children, homesteading on the edge of an impassable wilderness, exiled from their settlement when William defies the local church. When their newborn son vanishes and crops mysteriously fail, the family turns on one another.",
      Director: "Robert Eggers",
    },
    {
      Category: "Horror",
      Name: "the purge",
      Id: "62",
      img: "62.jpg",
      Date: 2013,
      Part: "2010s",
      Subject:
        "Given the country’s overcrowded prisons, the U.S. government begins to allow 12-hour periods of time in which all illegal activity is legal. During one of these free-for-alls, a family must protect themselves from a home invasion.",
      Director: "James DeMonaco",
    },
    {
      Category: "Horror",
      Name: "the others",
      Id: "63",
      img: "63.jpg",
      Date: 2001,
      Part: "2000s",
      Subject:
        "Grace is a religious woman who lives in an old house kept dark because her two children, Anne and Nicholas, have a rare sensitivity to light. When the family begins to suspect the house is haunted, Grace fights to protect her children at any cost in the face of strange events and disturbing visions.",
      Director: "Alejandro Amenábar",
    },
    {
      Category: "Horror",
      Name: "the shining",
      Id: "64",
      img: "64.jpg",
      Date: 1980,
      Part: "Older...",
      Subject:
        "Jack Torrance accepts a caretaker job at the Overlook Hotel, where he, along with his wife Wendy and their son Danny, must live isolated from the rest of the world for the winter. But they aren’t prepared for the madness that lurks within.",
      Director: "Stanley Kubrick",
    },
    {
      Category: "Horror",
      Name: "alien",
      Id: "65",
      img: "65.jpg",
      Date: 1979,
      Part: "Older...",
      Subject:
        "During its return to the earth, commercial spaceship Nostromo intercepts a distress signal from a distant planet. When a three-member team of the crew discovers a chamber containing thousands of eggs on the planet, a creature inside one of the eggs attacks an explorer. The entire crew is unaware of the impending nightmare set to descend upon them when the alien parasite planted inside its unfortunate host is birthed.",
      Director: " Ridley Scott",
    },
    {
      Category: "Horror",
      Name: "jaws",
      Id: "66",
      img: "66.jpg",
      Date: 1975,
      Part: "Older...",
      Subject:
        "When an insatiable great white shark terrorizes the townspeople of Amity Island, the police chief, an oceanographer and a grizzled shark hunter seek to destroy the blood-thirsty beast.",
      Director: "Steven Spielberg",
    },
    {
      Category: "Horror",
      Name: "psycho",
      Id: "67",
      img: "67.jpg",
      Date: 1960,
      Part: "Older...",
      Subject:
        "When larcenous real estate clerk Marion Crane goes on the lam with a wad of cash and hopes of starting a new life, she ends up at the notorious Bates Motel, where manager Norman Bates cares for his housebound mother. The place seems quirky, but fine… until Marion decides to take a shower.",
      Director: "Alfred Hitchcock",
    },
    {
      Category: "Science Fiction",
      Name: "2001 a space odyssey",
      Id: "68",
      img: "68.jpg",
      Date: 1968,
      Part: "Older...",
      Subject:
        "Humanity finds a mysterious object buried beneath the lunar surface and sets off to find its origins with the help of HAL 9000, the world’s most advanced super computer.",
      Director: " Stanley Kubrick",
    },
    {
      Category: "Science Fiction",
      Name: "star wars",
      Id: "69",
      img: "69.jpg",
      Date: 1977,
      Part: "Older...",
      Subject:
        "Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess and restore peace and justice in the Empire.",
      Director: "George Lucas",
    },
    {
      Category: "Science Fiction",
      Name: "the matrix",
      Id: "70",
      img: "70.jpg",
      Date: 1999,
      Part: "Older...",
      Subject:
        "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.",
      Director: "Lilly Wachowski, Lana Wachowski",
    },
    {
      Category: "Science Fiction",
      Name: "blade runner 2049",
      Id: "71",
      img: "71.jpg",
      Date: 2017,
      Part: "2010s",
      Subject:
        "Thirty years after the events of the first film, a new blade runner, LAPD Officer K, unearths a long-buried secret that has the potential to plunge what’s left of society into chaos. K’s discovery leads him on a quest to find Rick Deckard, a former LAPD blade runner who has been missing for 30 years.",
      Director: "Denis Villeneuve",
    },
    {
      Category: "Science Fiction",
      Name: "the fountain",
      Id: "72",
      img: "72.jpg",
      Date: 2006,
      Part: "2000s",
      Subject:
        "Spanning over one thousand years, and three parallel stories, The Fountain is a story of love, death, spirituality, and the fragility of our existence in this world.",
      Director: "Darren Aronofsky",
    },
    {
      Category: "Science Fiction",
      Name: "arrival",
      Id: "73",
      img: "73.jpg",
      Date: 2016,
      Part: "2010s",
      Subject:
        "Taking place after alien crafts land around the world, an expert linguist is recruited by the military to determine whether they come in peace or are a threat.",
      Director: "Denis Villeneuve",
    },
    {
      Category: "Science Fiction",
      Name: "moon",
      Id: "74",
      img: "74.jpg",
      Date: 2009,
      Part: "2000s",
      Subject:
        "With only three weeks left in his three year contract, Sam Bell is getting anxious to finally return to Earth. He is the only occupant of a Moon-based manufacturing facility along with his computer and assistant, GERTY. When he has an accident however, he wakens to find that he is not alone.",
      Director: "Duncan Jones",
    },
    {
      Category: "Science Fiction",
      Name: "rogue one: a star wars story",
      Id: "75",
      img: "75.jpg",
      Date: 2016,
      Part: "2010s",
      Subject:
        "A rogue band of resistance fighters unite for a mission to steal the Death Star plans and bring a new hope to the galaxy.",
      Director: "Gareth Edwards",
    },
    {
      Category: "Science Fiction",
      Name: "ex machina",
      Id: "76",
      img: "76.jpg",
      Date: 2015,
      Part: "2010s",
      Subject:
        "Caleb, a coder at the world’s largest internet company, wins a competition to spend a week at a private mountain retreat belonging to Nathan, the reclusive CEO of the company. But when Caleb arrives at the remote location he finds that he will have to participate in a strange and fascinating experiment in which he must interact with the world’s first true artificial intelligence, housed in the body of a beautiful robot girl.",
      Director: "Alex Garland",
    },
    {
      Category: "Science Fiction",
      Name: "contact",
      Id: "77",
      img: "77.jpg",
      Date: 1997,
      Part: "Older...",
      Subject:
        "Contact is a science fiction film about an encounter with alien intelligence. Based on the novel by Carl Sagan the film starred Jodie Foster as the one chosen scientist who must make some difficult decisions between her beliefs, the truth, and reality.",
      Director: "Robert Zemeckis",
    },
    {
      Category: "Fantasy",
      Name: "fantastic beasts  the secrets of dumbledore",
      Id: "78",
      img: "78.jpg",
      Date: 2022,
      Part: "2020s",
      Subject:
        "In an effort to thwart Grindelwald’s plans of raising pure-blood wizards to rule over all non-magical beings, Albus Dumbledore enlists his former student Newt Scamander, who agrees to help, though he’s unaware of the dangers that lie ahead. Lines are drawn as love and loyalty are tested, even among the truest friends and family, in an increasingly divided wizarding world.",
      Director: "David Yates",
    },
    {
      Category: "Fantasy",
      Name: "harry potter and the deathly hallows: part 2",
      Id: "79",
      img: "79.jpg",
      Date: 2011,
      Part: "2010s",
      Subject:
        "Harry, Ron and Hermione continue their quest to vanquish the evil Voldemort once and for all. Just as things begin to look hopeless for the young wizards, Harry discovers a trio of magical objects that endow him with powers to rival Voldemort’s formidable skills.",
      Director: "David Yates",
    },
    {
      Category: "Fantasy",
      Name: "the hobbit: an unexpected journey",
      Id: "80",
      img: "80.jpg",
      Date: 2012,
      Part: "2010s",
      Subject:
        "Bilbo Baggins, a hobbit enjoying his quiet life, is swept into an epic quest by Gandalf the Grey and thirteen dwarves who seek to reclaim their mountain home from Smaug, the dragon.",
      Director: "Peter Jackson",
    },
    {
      Category: "Fantasy",
      Name: "the dark knight rises",
      Id: "81",
      img: "81.jpg",
      Date: 2012,
      Part: "2010s",
      Subject:
        "Following the death of District Attorney Harvey Dent, Batman assumes responsibility for Dent’s crimes to protect the late attorney’s reputation and is subsequently hunted by the Gotham City Police Department. Eight years later, Batman encounters the mysterious Selina Kyle and the villainous Bane, a new terrorist leader who overwhelms Gotham’s finest. The Dark Knight resurfaces to protect a city that has branded him an enemy.",
      Director: "Christopher Nolan",
    },
    {
      Category: "Fantasy",
      Name: "harry potter and the deathly hallows: part 1",
      Id: "82",
      img: "82.jpg",
      Date: 2010,
      Part: "2010s",
      Subject:
        "Harry, Ron and Hermione walk away from their last year at Hogwarts to find and destroy the remaining Horcruxes, putting an end to Voldemort’s bid for immortality. But with Harry’s beloved Dumbledore dead and Voldemort’s unscrupulous Death Eaters on the loose, the world is more dangerous than ever.",
      Director: "David Yates",
    },
    {
      Category: "Fantasy",
      Name: "the chronicles of narnia",
      Id: "83",
      img: "83.jpg",
      Date: 2010,
      Part: "2010s",
      Subject:
        "This time around Edmund and Lucy Pevensie, along with their pesky cousin Eustace Scrubb find themselves swallowed into a painting and on to a fantastic Narnian ship headed for the very edges of the world.",
      Director: "Michael Apted",
    },
    {
      Category: "Fantasy",
      Name: "noah",
      Id: "84",
      img: "84.jpg",
      Date: 2014,
      Part: "2010s",
      Subject:
        "A man who suffers visions of an apocalyptic deluge takes measures to protect his family from the coming flood.",
      Director: "Darren Aronofsky",
    },
    {
      Category: "Fantasy",
      Name: "warcraft",
      Id: "85",
      img: "85.jpg",
      Date: 2016,
      Part: "2010s",
      Subject:
        "The peaceful realm of Azeroth stands on the brink of war as its civilization faces a fearsome race of invaders: orc warriors fleeing their dying home to colonize another. As a portal opens to connect the two worlds, one army faces destruction and the other faces extinction. From opposing sides, two heroes are set on a collision course that will decide the fate of their family, their people, and their home.",
      Director: " Duncan Jones",
    },
    {
      Category: "Fantasy",
      Name: "the lord of the rings: the two towers",
      Id: "86",
      img: "86.jpg",
      Date: 2002,
      Part: "2000s",
      Subject:
        "Frodo and Sam are trekking to Mordor to destroy the One Ring of Power while Gimli, Legolas and Aragorn search for the orc-captured Merry and Pippin. All along, nefarious wizard Saruman awaits the Fellowship members at the Orthanc Tower in Isengard.",
      Director: "Peter Jackson",
    },
    {
      Category: "Fantasy",
      Name: "harry potter and the prisoner of azkaban",
      Id: "87",
      img: "87.jpg",
      Date: 2004,
      Part: "2000s",
      Subject:
        "Harry, Ron and Hermione return to Hogwarts for another magic-filled year. Harry comes face to face with danger yet again, this time in the form of escaped convict, Sirius Black—and turns to sympathetic Professor Lupin for help.",
      Director: "Alfonso Cuarón",
    },
    {
      Category: "Fantasy",
      Name: "crouching tiger, hidden dragon",
      Id: "88",
      img: "88.jpg",
      Date: 2000,
      Part: "2000s",
      Subject:
        "Two warriors in pursuit of a stolen sword and a notorious fugitive are led to an impetuous, physically-skilled, teenage nobleman’s daughter, who is at a crossroads in her lif",
      Director: "Ang Lee",
    },
    {
      Category: "Fantasy",
      Name: "van helsing",
      Id: "89",
      img: "89.jpg",
      Date: 2004,
      Part: "2000s",
      Subject:
        "Famed monster slayer Gabriel Van Helsing is dispatched to Transylvania to assist the last of the Valerious bloodline in defeating Count Dracula. Anna Valerious reveals that Dracula has formed an unholy alliance with Dr. Frankenstein’s monster and is hell-bent on exacting a centuries-old curse on her family.",
      Director: "Stephen Sommers",
    },
    {
      Category: "Fantasy",
      Name: "the lord of the rings: the return of the king",
      Id: "90",
      img: "90.jpg",
      Date: 2003,
      Part: "2000s",
      Subject:
        "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron’s forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord’s realm.",
      Director: "Peter Jackson",
    },
    {
      Category: "Fantasy",
      Name: "the lord of the rings: the fellowship of the ring",
      Id: "91",
      img: "91.jpg",
      Date: 2001,
      Part: "2000s",
      Subject:
        "Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator. Along the way, a fellowship is formed to protect the ringbearer and make sure that the ring arrives at its final destination: Mt. Doom, the only place where it can be destroyed.",
      Director: "Peter Jackson",
    },
    {
      Category: "Fantasy",
      Name: "harry potter and the goblet of fire",
      Id: "92",
      img: "92.jpg",
      Date: 2005,
      Part: "2000s",
      Subject:
        "Harry starts his fourth year at Hogwarts, competes in the treacherous Triwizard Tournament and faces the evil Lord Voldemort. Ron and Hermione help Harry manage the pressure  but Voldemort lurks, awaiting his chance to destroy Harry and all that he stands for.",
      Director: "Mike Newell",
    },
    {
      Category: "Fantasy",
      Name: "jumanji",
      Id: "93",
      img: "93.jpg",
      Date: 1995,
      Part: "Older...",
      Subject:
        "When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan  an adult who’s been trapped inside the game for 26 years  into their living room. Alan’s only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures.",
      Director: "Joe Johnston",
    },
    {
      Category: "Fantasy",
      Name: "princess mononoke",
      Id: "94",
      img: "94.jpg",
      Date: 1997,
      Part: "Older...",
      Subject:
        "Ashitaka, a prince of the disappearing Emishi people, is cursed by a demonized boar god and must journey to the west to find a cure. Along the way, he encounters San, a young human woman fighting to protect the forest, and Lady Eboshi, who is trying to destroy it. Ashitaka must find a way to bring balance to this conflict.",
      Director: "Hayao Miyazaki",
    },
    {
      Category: "Fantasy",
      Name: "ghost in the shell",
      Id: "95",
      img: "95.jpg",
      Date: 1995,
      Part: "Older...",
      Subject:
        "In the year 2029, the barriers of our world have been broken down by the net and by cybernetics, but this brings new vulnerability to humans in the form of brain-hacking. When a highly-wanted hacker known as ‘The Puppetmaster’ begins involving them in politics, Section 9, a group of cybernetically enhanced cops, are called in to investigate and stop the Puppetmaster.",
      Director: "Mamoru Oshii",
    },
  ],
};

export const dataSlice = createSlice({
  name: "data",
  initialState: initialState,
  reducers: {
    // addCategory: (state, { payload }) => {
    //   state.categories = [...state.categories, payload];
    // },
  },
});

export const {} = dataSlice.actions;

export default dataSlice.reducer;
